// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/discovery.dart';
import 'api/file_system.dart';
import 'api/sftp_session.dart';
import 'api/simple.dart';
import 'api/transfer.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DiscoveredHost> dco_decode_StreamSink_discovered_host_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TransferProgress> dco_decode_StreamSink_transfer_progress_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DiscoveredHost dco_decode_box_autoadd_discovered_host(dynamic raw);

  @protected
  ConnectResult dco_decode_connect_result(dynamic raw);

  @protected
  DiscoveredHost dco_decode_discovered_host(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileNode dco_decode_file_node(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<FileNode> dco_decode_list_file_node(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DiscoveredHost? dco_decode_opt_box_autoadd_discovered_host(dynamic raw);

  @protected
  SortBy dco_decode_sort_by(dynamic raw);

  @protected
  TransferDirection dco_decode_transfer_direction(dynamic raw);

  @protected
  TransferProgress dco_decode_transfer_progress(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DiscoveredHost> sse_decode_StreamSink_discovered_host_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TransferProgress> sse_decode_StreamSink_transfer_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DiscoveredHost sse_decode_box_autoadd_discovered_host(
    SseDeserializer deserializer,
  );

  @protected
  ConnectResult sse_decode_connect_result(SseDeserializer deserializer);

  @protected
  DiscoveredHost sse_decode_discovered_host(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileNode sse_decode_file_node(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<FileNode> sse_decode_list_file_node(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DiscoveredHost? sse_decode_opt_box_autoadd_discovered_host(
    SseDeserializer deserializer,
  );

  @protected
  SortBy sse_decode_sort_by(SseDeserializer deserializer);

  @protected
  TransferDirection sse_decode_transfer_direction(SseDeserializer deserializer);

  @protected
  TransferProgress sse_decode_transfer_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_discovered_host_Sse(
    RustStreamSink<DiscoveredHost> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transfer_progress_Sse(
    RustStreamSink<TransferProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_discovered_host(
    DiscoveredHost self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connect_result(ConnectResult self, SseSerializer serializer);

  @protected
  void sse_encode_discovered_host(
    DiscoveredHost self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_node(FileNode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_node(List<FileNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_discovered_host(
    DiscoveredHost? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sort_by(SortBy self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_direction(
    TransferDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_progress(
    TransferProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
