// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/discovery.dart';
import 'api/file_system.dart';
import 'api/sftp_session.dart';
import 'api/simple.dart';
import 'api/transfer.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 182352914;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_sftp_client',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiTransferCancelTransfer({required String transferId});

  Future<ConnectResult> crateApiSftpSessionConnectSftp({
    required String host,
    required int port,
    required String username,
    required String password,
  });

  Future<void> crateApiFileSystemCopyLocal({
    required String srcPath,
    required String dstPath,
  });

  Future<void> crateApiFileSystemCopyRemote({
    required String srcPath,
    required String dstPath,
  });

  Future<void> crateApiFileSystemCreateLocalDir({required String path});

  Future<void> crateApiFileSystemCreateRemoteDir({required String path});

  Future<void> crateApiFileSystemDeleteLocal({required String path});

  Future<void> crateApiFileSystemDeleteRemoteDir({required String path});

  Future<void> crateApiFileSystemDeleteRemoteFile({required String path});

  Future<bool> crateApiSftpSessionDisconnectSftp();

  String? crateApiDiscoveryGetLocalIp();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  bool crateApiSftpSessionIsConnected();

  Future<List<FileNode>> crateApiFileSystemListLocalDir({
    required String path,
    required SortBy sortBy,
  });

  Future<List<FileNode>> crateApiFileSystemListRemoteDir({
    required String path,
    required SortBy sortBy,
  });

  Future<bool> crateApiSftpSessionPingSftp();

  Future<DiscoveredHost?> crateApiDiscoveryProbeHost({
    required String ip,
    required int port,
    required BigInt timeoutMs,
  });

  Future<void> crateApiFileSystemRenameLocal({
    required String oldPath,
    required String newPath,
  });

  Future<void> crateApiFileSystemRenameRemote({
    required String oldPath,
    required String newPath,
  });

  Stream<DiscoveredHost> crateApiDiscoveryScanNetwork({
    required String baseIp,
    required BigInt timeoutMs,
  });

  Stream<TransferProgress> crateApiTransferTransferFile({
    required String transferId,
    required TransferDirection direction,
    required String localPath,
    required String remotePath,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiTransferCancelTransfer({required String transferId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(transferId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferCancelTransferConstMeta,
        argValues: [transferId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferCancelTransferConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_transfer",
        argNames: ["transferId"],
      );

  @override
  Future<ConnectResult> crateApiSftpSessionConnectSftp({
    required String host,
    required int port,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connect_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSessionConnectSftpConstMeta,
        argValues: [host, port, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSessionConnectSftpConstMeta =>
      const TaskConstMeta(
        debugName: "connect_sftp",
        argNames: ["host", "port", "username", "password"],
      );

  @override
  Future<void> crateApiFileSystemCopyLocal({
    required String srcPath,
    required String dstPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(srcPath, serializer);
          sse_encode_String(dstPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemCopyLocalConstMeta,
        argValues: [srcPath, dstPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemCopyLocalConstMeta =>
      const TaskConstMeta(
        debugName: "copy_local",
        argNames: ["srcPath", "dstPath"],
      );

  @override
  Future<void> crateApiFileSystemCopyRemote({
    required String srcPath,
    required String dstPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(srcPath, serializer);
          sse_encode_String(dstPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemCopyRemoteConstMeta,
        argValues: [srcPath, dstPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemCopyRemoteConstMeta =>
      const TaskConstMeta(
        debugName: "copy_remote",
        argNames: ["srcPath", "dstPath"],
      );

  @override
  Future<void> crateApiFileSystemCreateLocalDir({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemCreateLocalDirConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemCreateLocalDirConstMeta =>
      const TaskConstMeta(debugName: "create_local_dir", argNames: ["path"]);

  @override
  Future<void> crateApiFileSystemCreateRemoteDir({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemCreateRemoteDirConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemCreateRemoteDirConstMeta =>
      const TaskConstMeta(debugName: "create_remote_dir", argNames: ["path"]);

  @override
  Future<void> crateApiFileSystemDeleteLocal({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemDeleteLocalConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemDeleteLocalConstMeta =>
      const TaskConstMeta(debugName: "delete_local", argNames: ["path"]);

  @override
  Future<void> crateApiFileSystemDeleteRemoteDir({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemDeleteRemoteDirConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemDeleteRemoteDirConstMeta =>
      const TaskConstMeta(debugName: "delete_remote_dir", argNames: ["path"]);

  @override
  Future<void> crateApiFileSystemDeleteRemoteFile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemDeleteRemoteFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemDeleteRemoteFileConstMeta =>
      const TaskConstMeta(debugName: "delete_remote_file", argNames: ["path"]);

  @override
  Future<bool> crateApiSftpSessionDisconnectSftp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSessionDisconnectSftpConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSessionDisconnectSftpConstMeta =>
      const TaskConstMeta(debugName: "disconnect_sftp", argNames: []);

  @override
  String? crateApiDiscoveryGetLocalIp() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiscoveryGetLocalIpConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryGetLocalIpConstMeta =>
      const TaskConstMeta(debugName: "get_local_ip", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiSftpSessionIsConnected() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSessionIsConnectedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSessionIsConnectedConstMeta =>
      const TaskConstMeta(debugName: "is_connected", argNames: []);

  @override
  Future<List<FileNode>> crateApiFileSystemListLocalDir({
    required String path,
    required SortBy sortBy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_sort_by(sortBy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_file_node,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemListLocalDirConstMeta,
        argValues: [path, sortBy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemListLocalDirConstMeta =>
      const TaskConstMeta(
        debugName: "list_local_dir",
        argNames: ["path", "sortBy"],
      );

  @override
  Future<List<FileNode>> crateApiFileSystemListRemoteDir({
    required String path,
    required SortBy sortBy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_sort_by(sortBy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_file_node,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemListRemoteDirConstMeta,
        argValues: [path, sortBy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemListRemoteDirConstMeta =>
      const TaskConstMeta(
        debugName: "list_remote_dir",
        argNames: ["path", "sortBy"],
      );

  @override
  Future<bool> crateApiSftpSessionPingSftp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSessionPingSftpConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSessionPingSftpConstMeta =>
      const TaskConstMeta(debugName: "ping_sftp", argNames: []);

  @override
  Future<DiscoveredHost?> crateApiDiscoveryProbeHost({
    required String ip,
    required int port,
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ip, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_discovered_host,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiscoveryProbeHostConstMeta,
        argValues: [ip, port, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryProbeHostConstMeta => const TaskConstMeta(
    debugName: "probe_host",
    argNames: ["ip", "port", "timeoutMs"],
  );

  @override
  Future<void> crateApiFileSystemRenameLocal({
    required String oldPath,
    required String newPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(oldPath, serializer);
          sse_encode_String(newPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemRenameLocalConstMeta,
        argValues: [oldPath, newPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemRenameLocalConstMeta =>
      const TaskConstMeta(
        debugName: "rename_local",
        argNames: ["oldPath", "newPath"],
      );

  @override
  Future<void> crateApiFileSystemRenameRemote({
    required String oldPath,
    required String newPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(oldPath, serializer);
          sse_encode_String(newPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileSystemRenameRemoteConstMeta,
        argValues: [oldPath, newPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileSystemRenameRemoteConstMeta =>
      const TaskConstMeta(
        debugName: "rename_remote",
        argNames: ["oldPath", "newPath"],
      );

  @override
  Stream<DiscoveredHost> crateApiDiscoveryScanNetwork({
    required String baseIp,
    required BigInt timeoutMs,
  }) {
    final sink = RustStreamSink<DiscoveredHost>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(baseIp, serializer);
            sse_encode_u_64(timeoutMs, serializer);
            sse_encode_StreamSink_discovered_host_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 21,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiDiscoveryScanNetworkConstMeta,
          argValues: [baseIp, timeoutMs, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDiscoveryScanNetworkConstMeta =>
      const TaskConstMeta(
        debugName: "scan_network",
        argNames: ["baseIp", "timeoutMs", "sink"],
      );

  @override
  Stream<TransferProgress> crateApiTransferTransferFile({
    required String transferId,
    required TransferDirection direction,
    required String localPath,
    required String remotePath,
  }) {
    final sink = RustStreamSink<TransferProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(transferId, serializer);
            sse_encode_transfer_direction(direction, serializer);
            sse_encode_String(localPath, serializer);
            sse_encode_String(remotePath, serializer);
            sse_encode_StreamSink_transfer_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 22,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiTransferTransferFileConstMeta,
          argValues: [transferId, direction, localPath, remotePath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTransferTransferFileConstMeta =>
      const TaskConstMeta(
        debugName: "transfer_file",
        argNames: [
          "transferId",
          "direction",
          "localPath",
          "remotePath",
          "sink",
        ],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DiscoveredHost> dco_decode_StreamSink_discovered_host_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TransferProgress> dco_decode_StreamSink_transfer_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DiscoveredHost dco_decode_box_autoadd_discovered_host(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_discovered_host(raw);
  }

  @protected
  ConnectResult dco_decode_connect_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ConnectResult(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      homeDir: dco_decode_String(arr[2]),
    );
  }

  @protected
  DiscoveredHost dco_decode_discovered_host(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DiscoveredHost(
      ip: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      hostname: dco_decode_String(arr[2]),
      responseMs: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FileNode dco_decode_file_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FileNode(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      isDir: dco_decode_bool(arr[2]),
      size: dco_decode_u_64(arr[3]),
      modifiedTimestamp: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<FileNode> dco_decode_list_file_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_file_node).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DiscoveredHost? dco_decode_opt_box_autoadd_discovered_host(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_discovered_host(raw);
  }

  @protected
  SortBy dco_decode_sort_by(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortBy.values[raw as int];
  }

  @protected
  TransferDirection dco_decode_transfer_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TransferDirection.values[raw as int];
  }

  @protected
  TransferProgress dco_decode_transfer_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TransferProgress(
      transferId: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      totalBytes: dco_decode_u_64(arr[2]),
      transferredBytes: dco_decode_u_64(arr[3]),
      percentage: dco_decode_f_64(arr[4]),
      speedBytesPerSec: dco_decode_f_64(arr[5]),
      etaSeconds: dco_decode_f_64(arr[6]),
      isComplete: dco_decode_bool(arr[7]),
      error: dco_decode_String(arr[8]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DiscoveredHost> sse_decode_StreamSink_discovered_host_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TransferProgress> sse_decode_StreamSink_transfer_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DiscoveredHost sse_decode_box_autoadd_discovered_host(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_discovered_host(deserializer));
  }

  @protected
  ConnectResult sse_decode_connect_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_homeDir = sse_decode_String(deserializer);
    return ConnectResult(
      success: var_success,
      message: var_message,
      homeDir: var_homeDir,
    );
  }

  @protected
  DiscoveredHost sse_decode_discovered_host(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ip = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_hostname = sse_decode_String(deserializer);
    var var_responseMs = sse_decode_u_64(deserializer);
    return DiscoveredHost(
      ip: var_ip,
      port: var_port,
      hostname: var_hostname,
      responseMs: var_responseMs,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FileNode sse_decode_file_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isDir = sse_decode_bool(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_modifiedTimestamp = sse_decode_i_64(deserializer);
    return FileNode(
      name: var_name,
      path: var_path,
      isDir: var_isDir,
      size: var_size,
      modifiedTimestamp: var_modifiedTimestamp,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<FileNode> sse_decode_list_file_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FileNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_file_node(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DiscoveredHost? sse_decode_opt_box_autoadd_discovered_host(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_discovered_host(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SortBy sse_decode_sort_by(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortBy.values[inner];
  }

  @protected
  TransferDirection sse_decode_transfer_direction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TransferDirection.values[inner];
  }

  @protected
  TransferProgress sse_decode_transfer_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transferId = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_transferredBytes = sse_decode_u_64(deserializer);
    var var_percentage = sse_decode_f_64(deserializer);
    var var_speedBytesPerSec = sse_decode_f_64(deserializer);
    var var_etaSeconds = sse_decode_f_64(deserializer);
    var var_isComplete = sse_decode_bool(deserializer);
    var var_error = sse_decode_String(deserializer);
    return TransferProgress(
      transferId: var_transferId,
      fileName: var_fileName,
      totalBytes: var_totalBytes,
      transferredBytes: var_transferredBytes,
      percentage: var_percentage,
      speedBytesPerSec: var_speedBytesPerSec,
      etaSeconds: var_etaSeconds,
      isComplete: var_isComplete,
      error: var_error,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_discovered_host_Sse(
    RustStreamSink<DiscoveredHost> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_discovered_host,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_transfer_progress_Sse(
    RustStreamSink<TransferProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_transfer_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_discovered_host(
    DiscoveredHost self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_discovered_host(self, serializer);
  }

  @protected
  void sse_encode_connect_result(ConnectResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.homeDir, serializer);
  }

  @protected
  void sse_encode_discovered_host(
    DiscoveredHost self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ip, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.hostname, serializer);
    sse_encode_u_64(self.responseMs, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_file_node(FileNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isDir, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_i_64(self.modifiedTimestamp, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_file_node(
    List<FileNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_file_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_discovered_host(
    DiscoveredHost? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_discovered_host(self, serializer);
    }
  }

  @protected
  void sse_encode_sort_by(SortBy self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_transfer_direction(
    TransferDirection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_transfer_progress(
    TransferProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.transferId, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_u_64(self.transferredBytes, serializer);
    sse_encode_f_64(self.percentage, serializer);
    sse_encode_f_64(self.speedBytesPerSec, serializer);
    sse_encode_f_64(self.etaSeconds, serializer);
    sse_encode_bool(self.isComplete, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
