// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Returns the local IPv4 address of this device.
String? getLocalIp() => RustLib.instance.api.crateApiDiscoveryGetLocalIp();

/// Scan the /24 subnet of the given `base_ip` for hosts with SSH (port 22) open.
Stream<DiscoveredHost> scanNetwork({
  required String baseIp,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiDiscoveryScanNetwork(
  baseIp: baseIp,
  timeoutMs: timeoutMs,
);

/// Probe a single IP:port to check if SSH is reachable.
Future<DiscoveredHost?> probeHost({
  required String ip,
  required int port,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiDiscoveryProbeHost(
  ip: ip,
  port: port,
  timeoutMs: timeoutMs,
);

/// A single discovered host on the LAN with SSH (port 22) open.
class DiscoveredHost {
  final String ip;
  final int port;
  final String hostname;
  final BigInt responseMs;

  const DiscoveredHost({
    required this.ip,
    required this.port,
    required this.hostname,
    required this.responseMs,
  });

  @override
  int get hashCode =>
      ip.hashCode ^ port.hashCode ^ hostname.hashCode ^ responseMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredHost &&
          runtimeType == other.runtimeType &&
          ip == other.ip &&
          port == other.port &&
          hostname == other.hostname &&
          responseMs == other.responseMs;
}
