// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `sort_entries`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// List the contents of a local directory.
Future<List<FileNode>> listLocalDir({
  required String path,
  required SortBy sortBy,
}) => RustLib.instance.api.crateApiFileSystemListLocalDir(
  path: path,
  sortBy: sortBy,
);

/// Create a new folder on the local filesystem.
Future<void> createLocalDir({required String path}) =>
    RustLib.instance.api.crateApiFileSystemCreateLocalDir(path: path);

/// Delete a local file or directory (recursive).
Future<void> deleteLocal({required String path}) =>
    RustLib.instance.api.crateApiFileSystemDeleteLocal(path: path);

/// Rename a local file or directory.
Future<void> renameLocal({required String oldPath, required String newPath}) =>
    RustLib.instance.api.crateApiFileSystemRenameLocal(
      oldPath: oldPath,
      newPath: newPath,
    );

/// List the contents of a remote directory over SFTP.
Future<List<FileNode>> listRemoteDir({
  required String path,
  required SortBy sortBy,
}) => RustLib.instance.api.crateApiFileSystemListRemoteDir(
  path: path,
  sortBy: sortBy,
);

/// Create a new directory on the remote server.
Future<void> createRemoteDir({required String path}) =>
    RustLib.instance.api.crateApiFileSystemCreateRemoteDir(path: path);

/// Delete a remote file.
Future<void> deleteRemoteFile({required String path}) =>
    RustLib.instance.api.crateApiFileSystemDeleteRemoteFile(path: path);

/// Delete a remote directory.
Future<void> deleteRemoteDir({required String path}) =>
    RustLib.instance.api.crateApiFileSystemDeleteRemoteDir(path: path);

/// Rename a remote file or directory.
Future<void> renameRemote({required String oldPath, required String newPath}) =>
    RustLib.instance.api.crateApiFileSystemRenameRemote(
      oldPath: oldPath,
      newPath: newPath,
    );

/// Copy a local file to another local path.
Future<void> copyLocal({required String srcPath, required String dstPath}) =>
    RustLib.instance.api.crateApiFileSystemCopyLocal(
      srcPath: srcPath,
      dstPath: dstPath,
    );

/// Copy a remote file to another remote path over SFTP.
Future<void> copyRemote({required String srcPath, required String dstPath}) =>
    RustLib.instance.api.crateApiFileSystemCopyRemote(
      srcPath: srcPath,
      dstPath: dstPath,
    );

/// A single file or directory entry used by both local and remote browsers.
class FileNode {
  final String name;
  final String path;
  final bool isDir;
  final BigInt size;
  final PlatformInt64 modifiedTimestamp;

  const FileNode({
    required this.name,
    required this.path,
    required this.isDir,
    required this.size,
    required this.modifiedTimestamp,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      modifiedTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileNode &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          size == other.size &&
          modifiedTimestamp == other.modifiedTimestamp;
}

/// Sorting criteria.
enum SortBy { name, date, size }
