// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_sftp`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SshHandler`, `SshState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `check_server_key`, `clone`, `fmt`

/// Connect to an SSH/SFTP server with username + password.
Future<ConnectResult> connectSftp({
  required String host,
  required int port,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSftpSessionConnectSftp(
  host: host,
  port: port,
  username: username,
  password: password,
);

/// Disconnect from the current server.
Future<bool> disconnectSftp() =>
    RustLib.instance.api.crateApiSftpSessionDisconnectSftp();

/// Check if we are currently connected.
bool isConnected() => RustLib.instance.api.crateApiSftpSessionIsConnected();

/// Ping active SFTP session to keep connection alive.
Future<bool> pingSftp() => RustLib.instance.api.crateApiSftpSessionPingSftp();

/// Result type returned to Dart after a connection attempt.
class ConnectResult {
  final bool success;
  final String message;
  final String homeDir;

  const ConnectResult({
    required this.success,
    required this.message,
    required this.homeDir,
  });

  @override
  int get hashCode => success.hashCode ^ message.hashCode ^ homeDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message &&
          homeDir == other.homeDir;
}
