// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `do_download`, `do_upload`, `report_progress`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Cancel an in‑progress transfer by its ID.
Future<void> cancelTransfer({required String transferId}) =>
    RustLib.instance.api.crateApiTransferCancelTransfer(transferId: transferId);

/// Start a file transfer (upload or download).
Stream<TransferProgress> transferFile({
  required String transferId,
  required TransferDirection direction,
  required String localPath,
  required String remotePath,
}) => RustLib.instance.api.crateApiTransferTransferFile(
  transferId: transferId,
  direction: direction,
  localPath: localPath,
  remotePath: remotePath,
);

/// Direction of a file transfer.
enum TransferDirection { localToRemote, remoteToLocal }

/// Real‑time metrics pushed to Flutter every ~100 ms.
class TransferProgress {
  final String transferId;
  final String fileName;
  final BigInt totalBytes;
  final BigInt transferredBytes;
  final double percentage;
  final double speedBytesPerSec;
  final double etaSeconds;
  final bool isComplete;
  final String error;

  const TransferProgress({
    required this.transferId,
    required this.fileName,
    required this.totalBytes,
    required this.transferredBytes,
    required this.percentage,
    required this.speedBytesPerSec,
    required this.etaSeconds,
    required this.isComplete,
    required this.error,
  });

  @override
  int get hashCode =>
      transferId.hashCode ^
      fileName.hashCode ^
      totalBytes.hashCode ^
      transferredBytes.hashCode ^
      percentage.hashCode ^
      speedBytesPerSec.hashCode ^
      etaSeconds.hashCode ^
      isComplete.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferProgress &&
          runtimeType == other.runtimeType &&
          transferId == other.transferId &&
          fileName == other.fileName &&
          totalBytes == other.totalBytes &&
          transferredBytes == other.transferredBytes &&
          percentage == other.percentage &&
          speedBytesPerSec == other.speedBytesPerSec &&
          etaSeconds == other.etaSeconds &&
          isComplete == other.isComplete &&
          error == other.error;
}
